#pragma once

#include <cxc/test/fail>
#include <cxc/test/scope>

namespace cxc
{
    namespace test
    {
        template <typename value_type>
        class check
        {
        public:
            check(const value_type& value, const scope& source, const char* file, int line)
                : m_value(value)
            {
            }

            void ensure(bool result, const std::string& message) const
            {
                if (!result)
                    throw fail(message, m_source, m_file, m_line);
            }

            template <typename another_type>
            void operator == (const another_type& another) const
            {
                ensure(m_value == another, "X == Y"); // TODO: lazy formatter
            }

            template <typename another_type>
            void operator != (const another_type& another) const
            {
                ensure(m_value != another, "X != Y"); // TODO: lazy formatter
            }

            template <typename another_type>
            void operator < (const another_type& another) const
            {
                ensure(m_value < another, "X < Y"); // TODO: lazy formatter
            }

            template <typename another_type>
            void operator > (const another_type& another) const
            {
                ensure(m_value > another, "X > Y"); // TODO: lazy formatter
            }

            template <typename another_type>
            void operator <= (const another_type& another) const
            {
                ensure(m_value <= another, "X <= Y"); // TODO: lazy formatter
            }

            template <typename another_type>
            void operator >= (const another_type& another) const
            {
                ensure(m_value >= another, "X >= Y"); // TODO: lazy formatter
            }

            void operator ! () const
            {
                ensure(!m_value, "!X"); // TODO: lazy formatter
            }

            template <class exception_type>
            void expect_exception()
            {
                try
                {
                    m_value();
                }
                catch (exception_type&)
                {
                    // OK
                }
                ensure(false, "Exception expected.");
            }

        private:
            const value_type& m_value;
            const scope& m_source;
            const char* file;
            int line;
        };
    }
}
